### ISSUE TITLE
Issue: VOPR fails to run on Windows

### ISSUE THREAD

**Issue by brentmaas** [coilhq/viewstamped-replication-made-famous#2]
### Description

Following the instructions in '_How can I run the implementation? How many batteries are included? Do you mean I can even run the VOPR?_' in the README on Windows will cause Zig to run into an error regarding an unexpected amount of arguments.

### Reproduction
- Clone the viewstamped-replication-made-famous repository
- Manually download the prebuilt Zig 0.8.0 linked in '_How can ... the VOPR?_'
- Try to run the VOPR with either given command (`zig.exe run src/simulator.zig -OReleaseSafe` or `zig.exe run src/simulator.zig -- 123`)

### Relevant system specs
- OS: Windows 10 Pro
- Zig version: 0.8.0
- Shell: both `cmd` and MSys2

### Console output
https://pastebin.com/KsbaVbYQ

**Comment by jorangreef** [comment]
Thanks @brentmaas we're on it.

**Comment by Snektron** [comment]
Seems to be caused by usage of nextPosix() here:
https://github.com/coilhq/viewstamped-replication-made-famous/blob/7ac6e5c03dd8f946635d2f884ff894fe89ab4f7d/src/simulator.zig#L33

**Comment by jorangreef** [comment]
Ah, of course! Thanks @Snektron

**Comment by jorangreef** [comment]
Would you be okay to hot patch it just by setting `const seed = seed_random`? That will bypass `nextPosix()` until we can have a fix on Monday (if you want to re-run a seed you can then just plug it in direct).

**Comment by nektro** [comment]
is there a reason why the generic`args.next();` wasn't used?

**Comment by jorangreef** [comment]
Not a good reason, I had just copy-pasta'd from our CLI which we did for Linux only at the time. Can I just swap `args.next()` in?

**Comment by nektro** [comment]
maybe not, seems to involve an allocator there. nevermind

https://github.com/ziglang/zig/blob/0.8.0/lib/std/process.zig#L460-L467

**Comment by brentmaas** [comment]
> Would you be okay to hot patch it just by setting `const seed = seed_random`? That will bypass `nextPosix()` until we can have a fix on Monday (if you want to re-run a seed you can then just plug it in direct).

Doing this and commenting out the line noted by @Snektron appears to be working for now. Thank you!

**Comment by jorangreef** [comment]
Great, you too! Hope to have a better experience on Windows soon with a `.bat` file to mirror the `.sh` script we have for Linux/macOS.
